#!/bin/bash

# backup
export _CONDA_BACKUP_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export _CONDA_BACKUP_CPATH=$CPATH
export _CONDA_BACKUP_CUDA_HOME=$CUDA_HOME
export _CONDA_BACKUP_CUB_HOME=$CUB_HOME
export _CONDA_BACKUP_CUDA_PATH=$CUDA_PATH


export CUDA_HOME=$CONDA_PREFIX
export CUDA_PATH=$CUDA_HOME
export CUB_HOME=$CUDA_HOME
export CPATH=$CUDA_HOME/include:$CPATH
export LD_LIBRARY_PATH=/opt/cuda/lib:$LD_LIBRARY_PATH
export TORCH_CUDA_ARCH_LIST="8.9"
